### ISSUE TITLE
Code doesn't work on input field

### ISSUE THREAD

**Issue by saihgal** [xLs51/Twemoji-Picker#1]
`$("#input-id").twemojiPicker();` doesn't work. 

However if I change my element "input-id" from `<input id="input-id"/>` to `<textarea id="input-id"></textarea>` instead of input, it works.

**Comment by xLs51** [comment]
Can you replace `<textarea id="twemoji-picker"></textarea>` by `<input id="twemoji-picker"/>` in the `index.html` demo and see if it works.

It is working for me so do you use any other jQuery plugin or something else ?
Which browser do you use ?

Thanks for the report !

**Comment by saihgal** [comment]
I tried what you suggested before raising this issue. It hadn't worked.
I used safari on OSX.

**Comment by xLs51** [comment]
Which version of OS X and safari are you using ?
It works correctly on the last version of safari with OS X El Capitain

**Comment by saihgal** [comment]
hmmm... I too am on Safari 9.0 and El Capitan

**Comment by xLs51** [comment]
Well, that's weird, do you see any errors in the developer tools ?

Just to confirm, this is not working ? https://jsfiddle.net/aaavkss8/
