### ISSUE TITLE
Init with text and emojis

### ISSUE THREAD

**Issue by petritz** [xLs51/Twemoji-Picker#2]
Is there a possibility to init this picker with some text and emojis?

**Comment by xLs51** [comment]
This is currently not available but that's a good idea, I'll work on it

**Comment by petritz** [comment]
Ok great!

**Comment by xLs51** [comment]
This is done !
You can add the option `init: ':thumbsup: Hello GitHub :hatching-chick: :heart:'` as stated [here](https://github.com/xLs51/Twemoji-Picker/blob/master/README.md#custom-options) :+1:

**Comment by petritz** [comment]
Really cool! But is it also possible to init with "&#x1f600"? Or is there a way to export the message as `" Test :heart:"`?

**Comment by xLs51** [comment]
You can use "&#x1f600" but it won't be rendered as a Twitter Emoji but depending of the browser.
I don't know what you mean by "export" but you will be able to save it to your database by using `:heart:` as explained [here](https://github.com/xLs51/Twemoji-Picker#database)
