### ISSUE TITLE
Input event callbacks

### ISSUE THREAD

**Issue by activestylus** [xLs51/Twemoji-Picker#5]
I have several listeners applied to my textareas (autogrow/counter/keyCodes/etc)

But I have no idea how to hook them into the twemoji textarea. 

How can I watch for events on the input?

**Comment by xLs51** [comment]
What kind of events are you looking for ?
I can create [custom event](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent) to listen, for example, when the content is changed, emote added etc.

**Comment by activestylus** [comment]
I'm basically listening for keyCodes. It's a simple chat app that submits the input contents when you hit Enter, so I guess the keydown event?

**Comment by xLs51** [comment]
If you want to submit the content, just add a form, a name to your textarea and a submit button.
Then either use PHP (e.g. `somewhere.php`) or JS onsubmit :

```
<form id="myform" action="somewhere.php" method="POST">
    <textarea id="twemoji-picker" name="somecontent"></textarea>
    <input type="submit" value="Submit">
</form>
```

**Comment by activestylus** [comment]
Yeah I'm not submitting the form because it's hooked into websockets. I'm actually doing `event.preventDefault()` right now, though I may just hack around that using the technique you just mentioned. Maybe put it on your roadmap? Would be kinda neat to have a few of the basics ('onChange','onBlur','onLoad') baked into the config options when you boot the script. I'm closing this because it's not so much an issue as much as a feature request at this point
