### ISSUE TITLE
Is it possible having picker at top of input?

### ISSUE THREAD

**Issue by lynx-r** [xLs51/Twemoji-Picker#6]
Hi!
Thank you for your lib!

Is it possible having picker at top of input?

**Comment by xLs51** [comment]
Hi, thank you !

Sure, I'll do it once I have some free time :smiley:

**Comment by xLs51** [comment]
You can now use the option `pickerPosition` with the value `top` to put the picker on top of the input :+1:

**Comment by lynx-r** [comment]
Thank you 👍
